# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - manipulator_controller
    - grip_controller

  manipulator_controller:
    type: FollowJointTrajectory
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
    action_ns: follow_joint_trajectory
    default: true
  grip_controller:
    type: GripperCommand
    joints:
      - finger_joint
    action_ns: gripper_cmd
    default: true